-- Run in Supabase SQL Editor. Then create an Auth user and add its UUID below.
create table if not exists public.support_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.tickets (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  name text not null check (char_length(trim(name)) between 2 and 100),
  email text not null check (char_length(email) between 5 and 254),
  category text not null check (category in ('General question','Download problem','Browser integration','Billing or license','Bug report','Other')),
  subject text not null check (char_length(trim(subject)) between 4 and 160),
  message text not null check (char_length(trim(message)) between 20 and 5000),
  status text not null default 'Open' check (status in ('Open','In Progress','Closed')),
  admin_reply text check (admin_reply is null or char_length(admin_reply) <= 5000),
  replied_at timestamptz
);

alter table public.support_admins enable row level security;
alter table public.tickets enable row level security;

revoke all on public.support_admins from anon, authenticated;
grant select on public.support_admins to authenticated;
drop policy if exists "Support admins can see their own membership" on public.support_admins;
create policy "Support admins can see their own membership"
  on public.support_admins for select to authenticated
  using (user_id = (select auth.uid()));

revoke all on public.tickets from anon, authenticated;
grant insert on public.tickets to anon, authenticated;
grant select, update on public.tickets to authenticated;
grant usage, select on sequence public.tickets_id_seq to anon, authenticated;

drop policy if exists "Visitors can submit support tickets" on public.tickets;
create policy "Visitors can submit support tickets"
  on public.tickets for insert to anon, authenticated
  with check (status = 'Open' and admin_reply is null and replied_at is null);

drop policy if exists "Support admins can read tickets" on public.tickets;
create policy "Support admins can read tickets"
  on public.tickets for select to authenticated
  using (exists (select 1 from public.support_admins a where a.user_id = (select auth.uid())));

drop policy if exists "Support admins can update tickets" on public.tickets;
create policy "Support admins can update tickets"
  on public.tickets for update to authenticated
  using (exists (select 1 from public.support_admins a where a.user_id = (select auth.uid())))
  with check (exists (select 1 from public.support_admins a where a.user_id = (select auth.uid())));

-- After creating an admin user in Supabase Authentication, run this to authorize it:
-- insert into public.support_admins (user_id)
-- select id from auth.users where email = 'you@example.com'
-- on conflict (user_id) do nothing;
